### ISSUE TITLE
Dumping additional properties of Pokémon.

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/KeySAVCoreJS#2]
Also dump locations such as hatch location, etc.

All things that are not dumped by standard KeySAV2 are subject to be added.

/ref Cu3PO42/KeySAVe#4

**Comment by WenSnake** [comment]
Dumping Language Tags would be nice. 

Requested Dump from chat:  "hmm does the hatch location state the traded/came from Kanto/Johto/etc. if they were transferred up?"

Minor Dumps: 6th Gen Pentagon Status, Ribbons

Super Minor: Pokerus status Cured/Carrier?/none

That's all I can think of

**Comment by Cu3PO42** [comment]
Those should all be implemented at this point. Some language files may be missing.

EDIT: Ribbons and location data still need localization data.

**Comment by Cu3PO42** [comment]
At this point it is only ribbons that are missing.

**Comment by Cu3PO42** [comment]
All but the Italian Ribbon Names have been gathered. Since there is no Italian translation of PKHeX, these will be extracted manually.

**Comment by Cu3PO42** [comment]
Instead of getting the names from PKHex they are now obtained directly from the games. Huge thanks to @SnowPhoenix for extracting the data for me!
